version: 2
updates:
- package-ecosystem: npm
  directory: "/blog"
  schedule:
    interval: daily
    time: "13:00"
  open-pull-requests-limit: 10
  target-branch: main
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.41
    - 15.0.0
  - dependency-name: postcss
    versions:
    - 8.2.10
    - 8.2.12
    - 8.2.7
    - 8.2.8
    - 8.2.9
  - dependency-name: mongoose
    versions:
    - 5.12.0
    - 5.12.1
    - 5.12.2
    - 5.12.3
    - 5.12.4
    - 5.12.5
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@testing-library/dom"
    versions:
    - 7.30.0
    - 7.30.1
    - 7.30.2
    - 7.30.3
  - dependency-name: "@vercel/node"
    versions:
    - 1.9.1
  - dependency-name: "@types/react"
    versions:
    - 17.0.3
  - dependency-name: swr
    versions:
    - 0.5.0
    - 0.5.2
    - 0.5.3
    - 0.5.4
  - dependency-name: "@auth0/nextjs-auth0"
    versions:
    - 1.2.0
  - dependency-name: "@types/react-dom"
    versions:
    - 17.0.2
  - dependency-name: ts-jest
    versions:
    - 26.5.3
  - dependency-name: "@sanity/types"
    versions:
    - 2.5.0
    - 2.6.0
  - dependency-name: date-fns
    versions:
    - 2.18.0
    - 2.19.0
  - dependency-name: next
    versions:
    - 10.0.8-canary.11
    - 10.0.8-canary.13
    - 10.0.8-canary.14
    - 10.0.8-canary.15
