name: 'Run tests and upload coverage'
on: [push, pull_request]

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies 
        run: npm install
      - name: Run Tests 
        run: npm test
      - uses: codecov/codecov-action@v2
        with:
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
