name: 'Run tests and upload coverage'
on: [push, pull_request]

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node Setup
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install Dependencies
        run: npm install
      - name: Run Tests
        run: npm run test:jest
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          flags: unittests # optional
          name: codecov-umbrella # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
      - name: Upload coverage to Code Climate
        uses: paambaati/codeclimate-action@v2.2.4
          env:
            CC_TEST_REPORTER_ID: 95eb076c1f357422f8ac333691cd4be0aec6471f43936b49381565f10af63655

