codecov:
  token: 801117ac-1725-4638-b286-539e42072046

flag_management:
  default_rules: # the rules that will be followed for any flag added, generally
    carryforward: true
    statuses:
      - name_prefix: project-
        type: project
        target: auto
        threshold: 1%
      - name_prefix: patch-
        type: patch
        target: 100%
  individual_flags: # exceptions to the default rules above, stated flag by flag
    - name: web #fill in your own flag name
      paths:
        - web/ #fill in your own path. Note, accepts globs, not regexes
      carryforward: true
      statuses:
        - name_prefix: new
          type: project
          target: 20%
        - name_prefix: new
          type: patch
          target: 80%
